#!/bin/sh
set -ex

USER_PASSWORD=$(cat /run/secrets/user_password)
# Create the non superuser
psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
    CREATE USER ${USER_NAME} WITH PASSWORD '${USER_PASSWORD}' NOCREATEDB NOCREATEROLE;
    CREATE DATABASE ${USER_DB} OWNER ${USER_NAME};

    REVOKE ALL PRIVILEGES ON DATABASE ${USER_DB} FROM PUBLIC;

    GRANT ALL PRIVILEGES ON DATABASE ${USER_DB} TO ${USER_NAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${USER_DB}" <<-EOSQL
    GRANT ALL ON SCHEMA public TO ${USER_NAME};
EOSQL
