#version: '3'

services:
    server:
        build:
          context: .
          dockerfile: Dockerfile-18
        image: 'postgres:18-alpine-ssl'
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_INITDB_ARGS="--data-checksums"
            - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
            - ENABLE_SSL=yes
            - TZ=Europe/Brussels
        env_file:
            - .env
        secrets:
            - postgres_password
        volumes:
            - data:/var/lib/postgresql

    adminer:
        image: 'library/adminer'
        restart: always
        ports:
            - 8080:8080

#    omnidb:
#        image: 'taivokasper/omnidb'
#        ports:
#            - 8082:8080
#            - 25482:25482
#        volumes:
#            - ./omnidb/config.py:/opt/OmniDB-3.0.3b/OmniDB/config.py

    pgadmin:
        image: 'dpage/pgadmin4'
        ports:
            - 5050:5050
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
            - PGADMIN_LISTEN_PORT=5050
        env_file:
          - .env
        secrets:
            - pgadmin_password

volumes:
    data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
