FROM postgres:17-alpine

COPY ./certs/out/postgres.key /var/lib/postgresql
COPY ./certs/out/postgres.crt /var/lib/postgresql

COPY ./certs/out/myCA.crt /var/lib/postgresql
COPY ./certs/out/myCA.crl /var/lib/postgresql

COPY ./ssl-conf.sh /usr/local/bin

RUN chown 0:70 /var/lib/postgresql/postgres.key \
        && chmod 640 /var/lib/postgresql/postgres.key \
        && chown 0:70 /var/lib/postgresql/postgres.crt \
        && chmod 640 /var/lib/postgresql/postgres.crt

RUN chown 0:70 /var/lib/postgresql/myCA.crt \
        && chmod 640 /var/lib/postgresql/myCA.crt \
        && chown 0:70 /var/lib/postgresql/myCA.crl \
        && chmod 640 /var/lib/postgresql/myCA.crl

ENTRYPOINT ["docker-entrypoint.sh"]

CMD [ "-c", "ssl=on" , "-c", "ssl_cert_file=/var/lib/postgresql/postgres.crt", \
    "-c", "ssl_key_file=/var/lib/postgresql/postgres.key", \
    "-c", "ssl_ca_file=/var/lib/postgresql/myCA.crt", \
    "-c", "ssl_crl_file=/var/lib/postgresql/myCA.crl" ]

